const chatsData = [
  {id: 0, name: 'John Doe', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 1, name: 'Samppa Nori', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Member', status: 'Active'},
  {id: 2, name: 'Estavan Lykos', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 3, name: 'Chetan Mohamed', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 4, name: 'Derick Maximinus', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/03/01', role: 'Member', status: 'Pending'},
  {id: 5, name: 'Friderik Dávid', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/21', role: 'Staff', status: 'Active'},
  {id: 6, name: 'Yiorgos Avraamu', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Member', status: 'Active'},
  {id: 7, name: 'Avram Tarasios', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 8, name: 'Quintin Ed', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 9, name: 'Enéas Kwadwo', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/03/01', role: 'Member', status: 'Pending'},
  {id: 10, name: 'Agapetus Tadeáš', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/21', role: 'Staff', status: 'Active'},
  {id: 11, name: 'Carwyn Fachtna', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Member', status: 'Active'},
  {id: 12, name: 'Nehemiah Tatius', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 13, name: 'Ebbe Gemariah', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 14, name: 'Eustorgios Amulius', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/03/01', role: 'Member', status: 'Pending'},
  {id: 15, name: 'Leopold Gáspár', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/21', role: 'Staff', status: 'Active'},
  {id: 16, name: 'Pompeius René', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Member', status: 'Active'},
  {id: 17, name: 'Paĉjo Jadon', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 18, name: 'Micheal Mercurius', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 19, name: 'Ganesha Dubhghall', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/03/01', role: 'Member', status: 'Pending'},
  {id: 20, name: 'Hiroto Šimun', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/21', role: 'Staff', status: 'Active'},
  {id: 21, name: 'Vishnu Serghei', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Member', status: 'Active'},
  {id: 22, name: 'Zbyněk Phoibos', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Staff', status: 'Banned'},
  {id: 23, name: 'Einar Randall', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/02/01', role: 'Admin', status: 'Inactive'},
  {id: 24, name: 'Félix Troels', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/03/21', role: 'Staff', status: 'Active'},
  {id: 25, name: 'Aulus Agmundr', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2018/01/01', role: 'Member', status: 'Pending'},
  {id: 42, name: 'Ford Prefex', messages: [{user_message: 'abc'}, {user_message: 'dddd'}, {client_message: 'aaa'}] ,  registered: '10:00 2001/05/21', role: 'Alien', status: 'Don\'t panic!'}
]

export default chatsData
